### PR TITLE
 Add the possibility to specify the HOST as an environment variable

### PR DESCRIPTION
**Pull request by tpreviero**
Hello again.
What about adding the possibility to specify the host also using an environment variable?
That'd be quite useful for testing purpose in "containerized" tests (thinking about "cloud oriented" approach and similar stuff).
What do you think? 🙃

### CODE REVIEW

**Comment by Code0x58** [comment]
Thanks, it looks good to me!

The history looks a little bit jiggled up due to me doing a _squash and merge_ on your last PR so it was a single commit. Do you mind me doing another for this?

**Comment by tpreviero** [comment]
Feel free to do whatever you want! 🙂

**Comment by Code0x58** [comment]
Thanks!

**Comment by Code0x58** [comment]
Out in [v0.2.1](https://github.com/Code0x58/gitlab-ci-validate/releases/tag/v0.2.1)

**Pull request merged**
